-- 7개의 문제!

-- 1. '컴퓨터정보' 학과에 속한 학생들의 학번, 이름, 평균시험점수를 출력하시오 (STUDENT, ENROL)
SELECT * FROM STUDENT;
SELECT * FROM ENROL;

SELECT 
    S.STU_NO 학번, 
    S.STU_NAME 이름, 
    ROUND(AVG(E.ENR_GRADE), 1) AS 평균시험점수
FROM STUDENT S
INNER JOIN ENROL E 
    ON S.STU_NO = E.STU_NO       
WHERE S.STU_DEPT = '컴퓨터정보'  
GROUP BY S.STU_NO, S.STU_NAME;




-- 2. '강종영' 교수의 과목 시험을 본 학생의 학번, 이름, 점수, 과목명을 출력하시오.(STUDENT, ENROL, SUBJECT)
SELECT * FROM STUDENT;
SELECT * FROM ENROL;
SELECT * FROM SUBJECT;

SELECT S.STU_NO, S.STU_NAME, E.ENR_GRADE, SUB.SUB_NAME
FROM STUDENT S
INNER JOIN ENROL E ON S.STU_NO = E.STU_NO
INNER JOIN SUBJECT SUB ON SUB.SUB_NO = E.SUB_NO
WHERE SUB.SUB_PROF = '강종영';




-- 3. 학생들의 이름, 시험을 본 개수를 출력하시오. 
-- 시험을 안본 사람은 출력을 안하거나 0으로 출력하거나 상관없음.(STUDENT, ENROL)
SELECT 
    S.STU_NAME, 
    COUNT(*) AS "시험 본 개수"
FROM STUDENT S
INNER JOIN ENROL E 
    ON S.STU_NO = E.STU_NO
GROUP BY S.STU_NAME
ORDER BY S.STU_NAME;





-- 4. 모든 학생들의 시험 평균 점수보다 높은 평균점수를 가지는 학생들의 학번, 이름, 평균점수를 출력하시오.(STUDENT, ENROL)
SELECT * FROM STUDENT;
SELECT * FROM ENROL;

SELECT T.STU_NO, T.STU_NAME, T.AVG_SCORE
FROM (
  SELECT S.STU_NO, S.STU_NAME, AVG(E.ENR_GRADE) AS AVG_SCORE
  FROM STUDENT S JOIN ENROL E ON S.STU_NO = E.STU_NO
  GROUP BY S.STU_NO, S.STU_NAME) T
WHERE T.AVG_SCORE > (SELECT AVG(ENR_GRADE) FROM ENROL);





-- 5. 사원번호, 이름, 급여 등급, 사수(MANAGER)이름을 출력하시오.(EMP, SALGRADE)
SELECT * FROM EMP;
SELECT * FROM SALGRADE;

SELECT E.ENAME, S.GRADE, E1.ENAME AS 사수
FROM EMP E
INNER JOIN SALGRADE S 
    ON E.SAL BETWEEN S.LOSAL AND S.HISAL
INNER JOIN EMP E1
    ON E.MGR = E1.EMPNO;




-- 6. 부서별 급여의 평균 등급을 출력하시오. - 부서명, 급여 평균 등급 출력(EMP, SALGRADE, DEPT)
SELECT * FROM SALGRADE;
SELECT * FROM EMP;
SELECT * FROM DEPT;

SELECT  D.DNAME, S.GRADE AS "평균 등급"
FROM EMP E
JOIN DEPT D 
    ON E.DEPTNO = D.DEPTNO
JOIN SALGRADE S
    ON E.SAL BETWEEN S.LOSAL AND S.HISAL
GROUP BY D.DNAME;







-- 7. 인문대학에 속한 교수의 이름을 모두 출력하시오.(PROFESSOR, DEPARTMENT)
SELECT * FROM PROFESSOR;
SELECT * FROM DEPARTMENT;

SELECT P.NAME AS "인문대학교수"
FROM DEPARTMENT D1
    JOIN DEPARTMENT D2 
    ON D2.PART = D1.DEPTNO
JOIN DEPARTMENT D3 
    ON D3.PART = D2.DEPTNO
JOIN PROFESSOR  P  
    ON P.DEPTNO = D3.DEPTNO
WHERE D1.DNAME = '인문대학';

