select * from STUDENT
WHERE STU_GENDER = 'F' AND STU_DEPT = '전기전자';

SELECT * FROM STUDENT
WHERE STU_GENDER = 'F' AND STU_DEPT = '전기전자';

SELECT STU_DEPT, ROUND(AVG(STU_HEIGHT),1)
FROM STUDENT
GROUP BY STU_DEPT;

SELECT * FROM PROFESSOR
WHERE LENGTH(ID) >= 6;

UPDATE PROFESSOR
SET
    PAY = PAY + 50
WHERE LENGTH(ID) >= 6;


ROLLBACK;

DELETE FROM PROFESSOR
WHERE LENGTH(ID) <6;

SELECT * FROM PROFESSOR;

INSERT INTO STUDENT(STU_NO, STU_NAME, STU_DEPT)
VALUES ('12341234', '홍길동', '기계');

INSERT INTO STUDENT
VALUES('12345678', '김철수', '전기전자', 1, 'A', 'M', 176, NULL);

ROLLBACK;

SELECT NAME, PAY, BONUS, PAY+BONUS
FROM PROFESSOR;      

--NVL
SELECT NAME, BONUS, NVL(BONUS, 0   )
FROM PROFESSOR;

--페이 보너너싀의 합이 300 이상인 사람을 구하시오.

select * FROM PRSOR,
SELECT * FROM PROFSSOR
WHERE PAY_BONUS,Q0)

--NVL2

SELECT BOUNUS, NVL2(BONUS, 1000 ,0)
FROM PROFESSOR;

SELECT NAME, 


-DECODE --자바의 ㅣ조건문 )IF

SELECT DECODFE(JOB, 'MANAGER', '매니저', '그외') FROM EMP

SELECT
    ENAME,
    JOB,
    DECODE(JOB, 'MANAGER','매니저', '그외')
FORM EMP;

--주민번호 7번째가 1,3이면 남자를 저아'

SELECT NAME, DECODE(SUBSTR(JUMIN, 7,1),11, '남자', 


SELECT * FROM PROFESIIOR;



SUBDENT
    CASE 
         WHEN PAY >=500 THEN '고소득'