--사용자 닉네임과 댓글 출력

SELECT U.NICKNAME, COUNT(*)AS 댓글갯수
FROM TBL_USER U
JOIN TBL_COMMENT C
    ON U.USERID = C.USERID
GROUP BY U.NICKNAME;




-- 각 게시글의 제목, 댓글 개수 출력
SELECT B.BOARDNO, B.TITLE 제목, COUNT(C.COMMENTNO) AS "댓글 개수"
FROM TBL_BOARD B
LEFT JOIN TBL_COMMENT C 
    ON B.BOARDNO = C.BOARDNO
GROUP BY B.BOARDNO, B.TITLE;


--게시글 제목, 내용, 작성자 닉네임, 댓글 개수(없으면 0) 출력
SELECT B.TITLE, U.NICKNAME, COUNT(C.COMMENTNO) AS 댓글개수
FROM TBL_BOARD B
JOIN TBL_USER U
    ON U.USERID = B.USERID          
LEFT JOIN TBL_COMMENT C
    ON B.BOARDNO = C.BOARDNO
GROUP BY B.BOARDNO, B.TITLE, U.NICKNAME;


SELECT 
    B.BOARDNO,
    B.TITLE,
    B.CONTENTS,
    B.CDATETIME,
    U.NICKNAME,
    NVL(T.CNT, 0) AS COMMENT_CNT
FROM TBL_BOARD B
JOIN TBL_USER U
    ON U.USERID = B.USERID
LEFT JOIN (
    SELECT 
        BOARDNO, 
        COUNT(COMMENTNO) AS CNT
    FROM TBL_COMMENT
    GROUP BY BOARDNO
) T 
    ON B.BOARDNO = T.BOARDNO;
    
    
    --CASE ~WHEN
    --PROFESSOR
    --1. PROFESSOR테이블에서 400 이상의 급여를 받으면 A, 
    -- 300~400 사이면 B, 나머지는 C로 출력
    -- 교수이름, 급여 등급 (A~C)
    
    
    SELECT * FROM PROFESSOR;
    SELECT * FROM SALGRADE;
    
    SELECT NAME,
     CASE 
        WHEN PAY >=400 THEN 'A'
        WHEN PAY >=300  THEN 'B'
        ELSE 'C'
    END AS PAY_GRADE
    FROM PROFESSOR;
    
